### ISSUE TITLE
"Error occurred while enabling ItemCase v2.0.0"

### ISSUE THREAD

**Issue by partyp770** [BleedObsidian/ItemCase#1]
I was really hyped to be able to use this plugin again, but I cant get it to work. I can't create itemcases or anything.

The plugin fails to start, so maybe that has something to do with it? Here's what it says in the logs if it helps:

`[00:34:39 ERROR]: Error occurred while enabling ItemCase v2.0.0 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant com.gmail.bleedobsidian.itemcase.LanguageTranslator.Language.EN-US
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_161]
	at com.gmail.bleedobsidian.itemcase.LanguageTranslator$Language.valueOf(LanguageTranslator.java:33) ~[?:?]
	at com.gmail.bleedobsidian.itemcase.configurations.ConfigFile.getLocale(ConfigFile.java:50) ~[?:?]
	at com.gmail.bleedobsidian.itemcase.ItemCaseCore.onEnable(ItemCaseCore.java:126) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-c3093ef-7e94e65]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]`

Am I missing a core plugin or something like that, or is my config messed up?

**Comment by partyp770** [comment]
Also, I removed every single plugin except for itemcase, and it still doesn't work. But in my lobby server, it does...?

I'm gonna lose my marbles if I cant get this plugin to work. D:

**Comment by partyp770** [comment]
Fixed! If this happens, delete the configuration file and then restart your server to generate a new one.

**Comment by partyp770** [comment]
I feel stupid because the solution was SO OBVIOUS.
